// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// novus_std/stdlib.novus
package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _novus_stdStdlibNovus = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x6c\x90\xc1\x4e\xc5\x20\x10\x45\xf7\xfd\x8a\x9b\xb7\x82\xc8\xc2\x7d\xd3\x2f\x31\xa6\x41\xde\x60\x31\x48\x9b\x81\xba\x31\xfd\x77\x33\xb4\xf8\x30\x71\x56\xed\xdc\xc3\x19\x86\x2f\xcb\xf8\xb4\x1b\x26\xf8\x3d\x29\xbf\x27\x67\xe0\xd6\x18\x35\xbe\x07\x00\x90\x3c\x14\x62\xfb\x16\xe9\x82\x24\x26\x67\xb0\xf1\xea\xee\x8d\x93\x0a\x1e\x2a\x52\x03\x34\xa6\x09\xcf\x7d\x2e\xc5\x54\xce\x83\xe3\x6f\xfb\x00\xc5\x4c\xff\x70\x6d\xae\x62\xca\xa5\x59\x0d\xb6\x3d\x2f\xaa\x3a\x8c\xdc\xc7\x29\x1f\xf8\x91\x6b\xad\x3b\x75\xfd\x3a\xce\xc6\x1f\xa5\xd0\x06\x2f\xaf\x7a\x1c\x8e\x71\x18\x64\xcd\x5c\x78\x76\x6b\x72\xb6\x5c\x8b\xc6\x25\x1b\xf0\x92\xdb\x0e\x22\xc8\x85\x43\x7a\x97\x48\xe3\xa9\xfd\x09\xf3\xf0\xf8\x10\x69\x66\xb2\xf7\x4b\xb3\xd9\xb2\xf4\xcf\x19\x43\xa2\x2c\x59\xe3\xe6\xda\x39\xb9\xb1\x9f\x34\x7f\xac\x21\xa9\x9a\x1a\xdc\x70\xab\x43\x7e\x02\x00\x00\xff\xff\xfc\xd5\xde\x77\xb2\x01\x00\x00")

func novus_stdStdlibNovusBytes() ([]byte, error) {
	return bindataRead(
		_novus_stdStdlibNovus,
		"novus_std/stdlib.novus",
	)
}

func novus_stdStdlibNovus() (*asset, error) {
	bytes, err := novus_stdStdlibNovusBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "novus_std/stdlib.novus", size: 434, mode: os.FileMode(420), modTime: time.Unix(1542323499, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"novus_std/stdlib.novus": novus_stdStdlibNovus,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"novus_std": &bintree{nil, map[string]*bintree{
		"stdlib.novus": &bintree{novus_stdStdlibNovus, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
