// Code generated by go-bindata. (@generated) DO NOT EDIT.
// sources:
// novus_std/stdlib.novus
package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _novus_stdStdlibNovus = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xb4\x51\x41\x4e\xc3\x40\x0c\xbc\xe7\x15\x73\x5c\x8b\x3d\x70\x0f\x79\x09\x42\x28\xb8\x5e\x1a\x69\x49\x2a\xef\x86\x0b\xca\xdf\x91\x9b\x3a\x4d\x05\x3d\xd6\xa7\xc4\x33\x1e\x7b\x66\xbf\x7b\xc5\x57\x7f\x42\x87\x34\x8f\x21\xcd\x23\x47\xf0\x94\x33\xe1\xa7\x01\x00\xc3\x87\x2a\xda\x7f\x64\xb9\x90\x0c\x16\x8e\x38\xe9\xc4\x07\xe7\x59\x0d\x09\x21\x8b\x13\x08\x5d\x87\xe7\x3d\x6e\xa5\x52\xd7\xc1\x76\x6b\x2f\x90\x5c\xe4\x1f\x9e\xef\x0d\x2a\xa5\xba\x6a\xb4\x1b\x38\x9c\x35\x22\xd2\xa0\x57\x88\x68\x27\x7a\xfe\x5a\xd6\xc6\x8d\x98\x91\x23\x5e\xdf\xa8\x6d\x96\xb6\x69\xcc\xa0\xca\x61\x66\x79\x48\x06\x2f\x0f\xcc\xe0\xc6\xbc\xdf\x72\x2f\x03\x33\x91\xec\xfa\x6d\x88\xae\x80\xa2\xc3\xb6\x60\xd7\x9f\xe6\xba\x1a\xe6\x90\x3c\x6c\xf5\x15\x7f\xcf\x53\x8a\x36\x62\xc9\xae\xc1\x96\xaa\xef\x3c\x8d\xdc\x5f\x64\x42\x3e\x96\x08\x3d\x16\x8f\xc4\x34\x4a\xd5\x61\xfc\x34\x88\xf0\xe4\x7f\xc6\xb1\x07\xfa\x0d\x00\x00\xff\xff\xbf\x9f\x29\x40\xa0\x02\x00\x00")

func novus_stdStdlibNovusBytes() ([]byte, error) {
	return bindataRead(
		_novus_stdStdlibNovus,
		"novus_std/stdlib.novus",
	)
}

func novus_stdStdlibNovus() (*asset, error) {
	bytes, err := novus_stdStdlibNovusBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "novus_std/stdlib.novus", size: 672, mode: os.FileMode(420), modTime: time.Unix(1542329612, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"novus_std/stdlib.novus": novus_stdStdlibNovus,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"novus_std": &bintree{nil, map[string]*bintree{
		"stdlib.novus": &bintree{novus_stdStdlibNovus, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}
